/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AddCourse {}
  interface AppAddassignments {}
  interface AppAssignmentinfo {}
  interface AppAssignments {}
  interface AppEditProfile {}
  interface AppFooter {}
  interface AppHome {}
  interface AppProfile {}
  interface AppRegistration {}
  interface AppRoot {}
  interface ColorPicker {
    'getSelectedColor': () => Promise<string>;
  }
  interface CourseInfo {}
  interface MyCourses {}
  interface MyCoursesCard {}
  interface NoCourses {}
}

declare global {


  interface HTMLAddCourseElement extends Components.AddCourse, HTMLStencilElement {}
  var HTMLAddCourseElement: {
    prototype: HTMLAddCourseElement;
    new (): HTMLAddCourseElement;
  };

  interface HTMLAppAddassignmentsElement extends Components.AppAddassignments, HTMLStencilElement {}
  var HTMLAppAddassignmentsElement: {
    prototype: HTMLAppAddassignmentsElement;
    new (): HTMLAppAddassignmentsElement;
  };

  interface HTMLAppAssignmentinfoElement extends Components.AppAssignmentinfo, HTMLStencilElement {}
  var HTMLAppAssignmentinfoElement: {
    prototype: HTMLAppAssignmentinfoElement;
    new (): HTMLAppAssignmentinfoElement;
  };

  interface HTMLAppAssignmentsElement extends Components.AppAssignments, HTMLStencilElement {}
  var HTMLAppAssignmentsElement: {
    prototype: HTMLAppAssignmentsElement;
    new (): HTMLAppAssignmentsElement;
  };

  interface HTMLAppEditProfileElement extends Components.AppEditProfile, HTMLStencilElement {}
  var HTMLAppEditProfileElement: {
    prototype: HTMLAppEditProfileElement;
    new (): HTMLAppEditProfileElement;
  };

  interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {}
  var HTMLAppFooterElement: {
    prototype: HTMLAppFooterElement;
    new (): HTMLAppFooterElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRegistrationElement extends Components.AppRegistration, HTMLStencilElement {}
  var HTMLAppRegistrationElement: {
    prototype: HTMLAppRegistrationElement;
    new (): HTMLAppRegistrationElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLColorPickerElement extends Components.ColorPicker, HTMLStencilElement {}
  var HTMLColorPickerElement: {
    prototype: HTMLColorPickerElement;
    new (): HTMLColorPickerElement;
  };

  interface HTMLCourseInfoElement extends Components.CourseInfo, HTMLStencilElement {}
  var HTMLCourseInfoElement: {
    prototype: HTMLCourseInfoElement;
    new (): HTMLCourseInfoElement;
  };

  interface HTMLMyCoursesElement extends Components.MyCourses, HTMLStencilElement {}
  var HTMLMyCoursesElement: {
    prototype: HTMLMyCoursesElement;
    new (): HTMLMyCoursesElement;
  };

  interface HTMLMyCoursesCardElement extends Components.MyCoursesCard, HTMLStencilElement {}
  var HTMLMyCoursesCardElement: {
    prototype: HTMLMyCoursesCardElement;
    new (): HTMLMyCoursesCardElement;
  };

  interface HTMLNoCoursesElement extends Components.NoCourses, HTMLStencilElement {}
  var HTMLNoCoursesElement: {
    prototype: HTMLNoCoursesElement;
    new (): HTMLNoCoursesElement;
  };
  interface HTMLElementTagNameMap {
    'add-course': HTMLAddCourseElement;
    'app-addassignments': HTMLAppAddassignmentsElement;
    'app-assignmentinfo': HTMLAppAssignmentinfoElement;
    'app-assignments': HTMLAppAssignmentsElement;
    'app-edit-profile': HTMLAppEditProfileElement;
    'app-footer': HTMLAppFooterElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-registration': HTMLAppRegistrationElement;
    'app-root': HTMLAppRootElement;
    'color-picker': HTMLColorPickerElement;
    'course-info': HTMLCourseInfoElement;
    'my-courses': HTMLMyCoursesElement;
    'my-courses-card': HTMLMyCoursesCardElement;
    'no-courses': HTMLNoCoursesElement;
  }
}

declare namespace LocalJSX {
  interface AddCourse {}
  interface AppAddassignments {}
  interface AppAssignmentinfo {}
  interface AppAssignments {}
  interface AppEditProfile {}
  interface AppFooter {}
  interface AppHome {}
  interface AppProfile {}
  interface AppRegistration {}
  interface AppRoot {}
  interface ColorPicker {}
  interface CourseInfo {}
  interface MyCourses {}
  interface MyCoursesCard {}
  interface NoCourses {}

  interface IntrinsicElements {
    'add-course': AddCourse;
    'app-addassignments': AppAddassignments;
    'app-assignmentinfo': AppAssignmentinfo;
    'app-assignments': AppAssignments;
    'app-edit-profile': AppEditProfile;
    'app-footer': AppFooter;
    'app-home': AppHome;
    'app-profile': AppProfile;
    'app-registration': AppRegistration;
    'app-root': AppRoot;
    'color-picker': ColorPicker;
    'course-info': CourseInfo;
    'my-courses': MyCourses;
    'my-courses-card': MyCoursesCard;
    'no-courses': NoCourses;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'add-course': LocalJSX.AddCourse & JSXBase.HTMLAttributes<HTMLAddCourseElement>;
      'app-addassignments': LocalJSX.AppAddassignments & JSXBase.HTMLAttributes<HTMLAppAddassignmentsElement>;
      'app-assignmentinfo': LocalJSX.AppAssignmentinfo & JSXBase.HTMLAttributes<HTMLAppAssignmentinfoElement>;
      'app-assignments': LocalJSX.AppAssignments & JSXBase.HTMLAttributes<HTMLAppAssignmentsElement>;
      'app-edit-profile': LocalJSX.AppEditProfile & JSXBase.HTMLAttributes<HTMLAppEditProfileElement>;
      'app-footer': LocalJSX.AppFooter & JSXBase.HTMLAttributes<HTMLAppFooterElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-profile': LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
      'app-registration': LocalJSX.AppRegistration & JSXBase.HTMLAttributes<HTMLAppRegistrationElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'color-picker': LocalJSX.ColorPicker & JSXBase.HTMLAttributes<HTMLColorPickerElement>;
      'course-info': LocalJSX.CourseInfo & JSXBase.HTMLAttributes<HTMLCourseInfoElement>;
      'my-courses': LocalJSX.MyCourses & JSXBase.HTMLAttributes<HTMLMyCoursesElement>;
      'my-courses-card': LocalJSX.MyCoursesCard & JSXBase.HTMLAttributes<HTMLMyCoursesCardElement>;
      'no-courses': LocalJSX.NoCourses & JSXBase.HTMLAttributes<HTMLNoCoursesElement>;
    }
  }
}


